### PR TITLE
Run of "go work sync"

### PR DESCRIPTION
**Pull request by pcdummy**
Updates the nats plugins to dismiss a dependabot alert

Signed-off-by: René Jochum <rene@jochum.dev>

### CODE REVIEW

**Comment by pcdummy** [comment]
I used the following command to update all dependencies:

```bash
find . -name 'go.mod' -type f -print0 | xargs -0 -P $(nproc) -I {} -- /bin/bash -c 'pushd $(dirname $1); go get -u ./...; go mod tidy; popd' _ '{}'
```

It seems to break v4/acme/certmagic tests and maybe others.

**Comment by xpunch** [comment]
Should you help fixing failed unit tests?

**Comment by pcdummy** [comment]
I'm afraid that more stuff than just unit tests break on that "big" update, I can put it on my todo but still it'll break peoples experience with these plugins.

**Comment by xpunch** [comment]
OK, then can you only upgrade the nats plugins which your are using now?
We cannot accept those failed unit tests.

**Pull request closed without merging**
