### PR TITLE
Add NATS JetStream Store Plugin

### PR DESCRIPTION
**Pull request by Davincible**
I have created a Store plugin for NATS JetStream, as NATS offers both a keystore and an object store, I found it useful to use NATS for both my pub/sub, events, and store.

For this plugin I used the `ObjectStore`, allowing you to store an unlimited amount of data within a single key, as the keystore is limited to 1mb.

Test coverage is 86%

### CODE REVIEW

**Comment by Davincible** [comment]
@xpunch

**Comment by xpunch** [comment]
@Davincible seams the unit tests failed

**Comment by Davincible** [comment]
It's an issue with the nats server. They pas 8/10 times locally, but sometimes it throws the context deadline exceeded like here. Tests themselves pass

**Comment by xpunch** [comment]
I've invited you as member of this org, which was created by asim, and very welcome for those who willing to contribute to go micro.

**Pull request merged**
