### PR TITLE
feat(registry): new registry Polaris

### PR DESCRIPTION
**Pull request by keepstep**
new registry polaris

### CODE REVIEW

**Comment by Davincible** [comment]
Thanks a lot for writing this plugin! Keen to have this plugin added.

We recently added a better CI pipeline, with lining and testing. Please merge the PR I created on your fork so that the new github actions will be integrated and run on this PR.

The Linter will give you some issues, please fix them (as best as possible).

Could you also add some unit tests? If you're not sure where to start take a look at the tests in the other registry plugins, or the core framework, or ask for help :)

**Comment by keepstep** [comment]
maybe it‘s hard to pass the unit tests because it lay on the deployment of polaris。
just like the plugin of registry/etcd, also no unit tests, i think is the same reason.

**Comment by Davincible** [comment]
Since Polaris is written in Go, you can start a Polaris server from the tests. See [this](https://github.com/polarismesh/polaris/blob/bc5d8ec00f658521d19e1f5b41b0e89b3c62dd38/bootstrap/server.go#L58). We also this for e.g. the NATS tests.

Also, could you merge with the main branch again? The hooks for the github actions were broken, they're now fixed.

**Comment by keepstep** [comment]
thanks for reminding，i will try it

**Comment by Davincible** [comment]
If you need any help let me know

**Comment by keepstep** [comment]
unit tests went wrong that i can not handle, maybe is bug of polaris.
but i run unit tests on windows and passed.

**Comment by Davincible** [comment]
I will have a look :)

Thanks for adding the tests

**Comment by Davincible** [comment]
I've tried to fix the tests but for some reason, it keeps failing here. Everything works locally, although I have also had to fix some issues.

I think Polaris is quite unstable, as also locally for the benchmarks I had to make sure each round the name of the service is different, as otherwise, Polaris would mark them as unhealthy.

I think that maybe the Github actions VM is too small or something, causing some issues. After observing multiple runs it always fails to deregister fully, even though it says it did deregister. 

I think this is an upstream bug at Polaris itself.

**Comment by Davincible** [comment]
Looks like we need to disable cache:
https://github.com/polarismesh/polaris/issues/732

**Comment by Davincible** [comment]
@keepstep I've refactored the code to remove the linting issues.

Was there any particular reason why you didn't implement the watcher? Polaris seems to support watch operations.

**Comment by keepstep** [comment]
👍。I didn't study it carefully and am not familiar with Polaris watch. You can try it.

**Comment by Davincible** [comment]
I've added a notice to the readme to say it's not implemented yet. If it's okay with you I can merge the PR now

**Review by Davincible — APPROVED** [review]

**Pull request merged**
