### PR TITLE
feat(wrapper/service): Add subscriber wrapper

### PR DESCRIPTION
**Pull request by dbereza-machinify**
Add a matching option provided for clients/handlers to add the service into the context for subscribers, to allow subscription handlers to access the service and configured components.

### CODE REVIEW

**Comment by xpunch** [comment]
```
The only reason a Call wrapper existed was for convenience but if we have wrappers for all methods its messy. Wrappers should likely be an external construct, not one baked into the client.
```
https://github.com/asim/go-micro/pull/2385

**Comment by dbereza-machinify** [comment]
Hmm, well in this case this isn't a wrapper for publishing but rather subscribing, where the framework is the one that invokes the subscription handler with parameters.

Currently there's no good way to get access to the service in a subscription handler without making it a global or something, from what I can tell. Is there a good way around this without adding this wrapper?

**Comment by xpunch** [comment]
Sorry, I misunderstood your issue.

**Review by xpunch — APPROVED** [review]

**Comment by dbereza-machinify** [comment]
Thanks!

**Pull request merged**
